Patch for Multi API Auth tokens
RestComm/Restcomm-Connect pull request #2201
Opened 2017-06-07 06:20 UTC by arslan70

Please review the changes for a patch for implementing [Multiple API Auth tokens](https://github.com/RestComm/Restcomm-Connect/issues/2164)

**Changes Overview**
===DB/DAO Changes===
1) Changed mybatis version from 3.2.2 to 3.4.4
2) Removed auth_token  field from restcomm_accounts table 
3) Added table restcomm_accounts_auth_tokens
4) Changed Mybatis accounts.xml file
5) Changed Initialization DB Script

===Code Changes===
1) Endpoints added for adding, deleting and listing auth tokens in http module

- AddAuthToken()
- GetAuthTokens()
- DeleteAuthToken()

2) Authentication logic changed for matching password. Matching is done against a list in containsAuthToken(token) in Account.java

3) Added test cases related to auth tokens in AccountsDaoTest

2017-06-07 16:02 UTC, scottbarstow commented on restcomm/restcomm.dao/src/main/java/org/restcomm/connect/dao/mybatis/MybatisAccountsDao.java
> +            System.out.println("Adding Account tokens token:"+token);
Need to pull this and use logging. No System.outs...

2017-06-07 16:37 UTC, scottbarstow commented on restcomm/restcomm.dao/src/main/java/org/restcomm/connect/dao/mybatis/MybatisAccountsDao.java
> +            System.out.println("Updating Account tokens token:"+token);
Another system out

2017-06-07 21:13 UTC, scottbarstow commented on restcomm/restcomm.dao/src/main/java/org/restcomm/connect/dao/entities/Account.java
> +        System.out.println("token passed for authentication:" + token);
More system outs. :)

2017-06-07 21:28 UTC, scottbarstow commented
@arslan70 Have you thought through how we'd migrate data upon install of this patch? I don't see a migration script to move the data from the current table to the new table as a part of the update.

Something to think about. This all looks really great as a first cut. I've made a few small notes, will look at it again in the next couple days.

2017-06-08 06:43 UTC, arslan70 commented
Hey Scott, I just removed the System.outs

I'll work on the migration script. Is it possible to have a sample data table for me to run and test the script?

2017-06-08 12:31 UTC, scottbarstow commented
@arslan70 Just create a test case that creates a bunch of accounts and then executes the migration, then tests the results. That would be best. We can also do full migration testing, but the first step is a test or set of tests.

2017-06-20 07:20 UTC, deruelle commented
Thanks @arslan70 

@maria-farooq @gvagenas can you please help with the review ?

2017-08-17 10:16 UTC, gvagenas requested changes
@arslan70 Thanks for your work here.
There are several issues that need to be taken care.

Several parts of the code using just the first auth token which is a bad hard coded limitation I believe.

Code must be ready to handle old DB schema.

Also all the tests I run in the testsuite failed because HSQLDB script is not updated. You need to take care of that also.

2017-08-17 10:16 UTC, gvagenas commented on restcomm/restcomm.dao/src/main/java/org/restcomm/connect/dao/entities/shiro/Realm.java
> +                authToken = account.getAuthToken().get(0).getAuthToken();//Not sure if this is the right approach
@arslan70 why use the 1st auth token only? This doesn't seem right. Even though as far as I remember this is not used anyore.

2017-08-17 10:16 UTC, gvagenas commented on restcomm/restcomm.http/src/main/java/org/restcomm/connect/http/AccountsEndpoint.java
> +        final List<AuthToken> authToken =new ArrayList<>();
@arslan70 What if I want to create an account and provide multiple auth tokens? We need to take care of that also.

2017-08-17 10:16 UTC, gvagenas commented on restcomm/restcomm.http/src/main/java/org/restcomm/connect/http/AccountsEndpoint.java
> +                authToken.add(new AuthToken(account.getSid(), hash, "default"));
@arslan70 same here. We need to take care account update with multiple auth tokens. If an existing account has already multiple auth tokens, the method here will replace all auth token with a single one

2017-08-17 10:16 UTC, gvagenas commented on restcomm/restcomm.http/src/main/java/org/restcomm/connect/http/AccountsEndpoint.java
> +                rcmlServerApi.transmitNotifications(notifications, notifier.getSid().toString(), notifier.getAuthToken().get(0).getAuthToken());
@arslan70 using only the first auth token will bring a hard coded limitation.

2017-08-17 10:16 UTC, gvagenas commented on restcomm/restcomm.http/src/main/java/org/restcomm/connect/http/converter/AccountConverter.java
> +        writeAuthToken(account.getAuthToken(), object);
@arslan70 why write only the first auth token? This doesn't seem right

2017-08-23 17:28 UTC, arslan70 commented
Hi George, thanks for the review and suggestions. I'll pick up the work but I just wanted to let you know that there was another issue I was working on for which I did a [PR](https://github.com/RestComm/Restcomm-Connect/pull/2294). That PR handles the password for web. This PR handles token authentication and management from API's perspective. So I'm picking it up after some time and may need your help. Right now can you review this PR again ignoring the code which is written for password authentication/management?

2017-08-23 17:34 UTC, arslan70 commented
@gvagenas 

> Also all the tests I run in the testsuite failed because HSQLDB script is not updated. You need to take care of that also.
Let's get this working after my branch is updated and github is telling me there are some conflicts to be resolved :(

2026-02-15 10:08 UTC, closed without merging